version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
#   command: --check-caps false
    ports: 
      - 32782:32782
      - 32783:32783
      - 32784:32784
      - 7878:7878
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
