#Define HL7 message types and segment descriptions
hl7_message_types = {
    'ACK': 'Acknowledgement',
    'ADR_A19': 'Patient query',
    'ADT_A01': 'Admit/Visit Notification',
    'ADT_A02': 'Transfer Patient',
    'ADT_A03': 'Discharge/End Visit',
    'ADT_A05': 'Pre-admission',
    'ADT_A06': 'Change an outpatient to an inpatient',
    'ADT_A09': 'Patient Departed',
    'ADT_A12': 'Cancel transfer',
    'ADT_A15': 'Pending transfer',
    'ADT_A16': 'Pending Discharge',
    'ADT_A17': 'Swap patients',
    'ADT_A18': 'Merge patient information',
    'ADT_A20': 'Bed status update',
    'ADT_A21': 'Patient goes on a leave',
    'ADT_A24': 'Link patient information',
    'ADT_A30': 'Merge person information',
    'ADT_A37': 'Unlink Patient Information',
    'ADT_A38': 'Cancel pre-admit',    
    'ADT_A43': 'Move patient information',
    'ADT_A45': 'Move Visit Information',
    'ADT_A50': 'Change visit number',
    'ADT_A54': 'Change Attending Doctor',
    'ADT_A60': 'Update Allergy Information',
    'ADT_A61': 'Change consulting doctor',
    'BAR_P01': 'Add patient accounts',
    'BAR_P02': 'Add patient accounts',
    'BAR_P05': 'Update account',
    'BAR_P06': 'End account',
    'BAR_P10': 'Transmit Ambulatory Payment',
    'BAR_P12': 'Update Diagnosis/Procedure',
    'BPS_O29': 'Blood product dispense status',
    'BRP_O30': 'Blood product dispense status ACK',
    'BRT_O32': 'Blood product transfusion ACK',
    'BTS_O31': 'Blood product transfusion/disposition',
    'CRM_C01': 'Register a patient on a clinical trial',
    'CSU_C09': 'Automated time intervals for reporting',
    'DFT_P03': 'Detail Financial Transactions',
    'DFT_P11': 'Financial Details Report',
    'DOC_T12': 'Document query',
    'DSR_Q01': 'Query sent for immediate response',
    'DSR_Q03': 'Deferred response to a query',
    'EAC_U07': 'Automated equipment command',
    'EAN_U09': 'Automated equipment notification',
    'EAR_U08': 'Automated equipment response',
    'EDR_R07': 'Enhanced Display Response',
    'EQQ_Q04': 'Embedded query language query',
    'ERP_R09': 'Event Replay Response',
    'ESR_U02': 'Electronic Status Report',
    'ESU_U01': 'Electronic Status Update',
    'INR_U06': 'Automated equipment inventory request',
    'INU_U05': 'Automated equipment inventory update',
    'LSU_U12': 'Automated equipment log/service update',
    'MDM_T01': 'Original document notification',
    'MDM_T02': 'Original document notification and content',
    'MFN_M01': 'Master file not otherwise specified',
    'MFN_M02': 'Master file - staff practitioner',
    'MFN_M03': 'Master file - test/observation',
    'MFN_M04': 'Master files charge description',
    'MFN_M05': 'Patient location master file',
    'MFN_M07': 'Clinical study without phases',
    'MFN_M08': 'Test/observation (numeric) master file',
    'MFN_M09': 'Test/observation (categorical) master file',
    'MFN_M10': 'Test /observation batteries master file',
    'MFN_M11': 'Test/calculated observations master file',
    'MFN_M12': 'Master file notification message',
    'MFN_M13': 'Master file notification - general',
    'MFN_M15': 'Inventory item master file notification',    
    'NMQ_N01': 'Application management query message',   
    'OMB_O27': 'Blood product order',
    'OMD_O03': 'Diet order',
    'OMG_O19': 'General clinical order',
    'OMI_O23': 'Imaging order',
    'OML_O21': 'Laboratory order',
    'OML_O33': 'Laboratory order for multiple orders',
    'OML_O35': 'Laboratory order for a single container',
    'OMN_O07': 'Non-stock requisition order',
    'OMP_O09': 'Pharmacy/treatment order',
    'OMS_O05': 'Stock requisition order',
    'ORB_O28': ' Blood product order acknowledgment',
    'ORD_O04': 'Order Request Data',
    'ORF_R04': 'Diet order acknowledgment',
    'ORG_O20': 'General clinical order response',
    'ORI_O24': 'Imaging order response',
    'ORL_O22': 'General laboratory order response ',
    'ORL_O34': 'Laboratory order response',
    'ORL_O36': 'Laboratory order response (container)',
    'ORM_O01': 'Order Message',
    'ORN_O08': 'Non-stock requisition acknowledgment',
    'ORP_O10': 'Pharmacy/treatment order acknowledgment',
    'ORR_O02': 'Order Response',
    'ORS_O06': 'Stock requisition acknowledgment',
    'ORU_R01': 'Order Result',
    'ORU_R30': 'Unsolicited Observation Without Existing Order ',
    'OSQ_Q06': 'Order Status Query',
    'OSR_Q06': 'Order Status Response',
    'OUL_R21': 'Unsolicited laboratory observation',
    'OUL_R22': 'Unsolicited laboratory observation',
    'OUL_R23': 'Unsolicited Specimen Container',
    'OUL_R24': 'Unsolicited Order Oriented Observation',
    'PEX_P07': 'Unsolicited initial individual product rep',
    'PGL_PC6': 'PC/ Goal add',
    'PPG_PCG': 'pathway (goal-oriented) add',
    'PPP_PCB': 'PC/ pathway (problem-oriented) add',
    'PPR_PC1': 'PC/ problem add',
    'PPT_PCL': 'PC/ pathway (goal-oriented) query response',
    'PPV_PCA': 'PC/ goal response',
    'PRR_PC5': 'PC/ problem response',
    'PTR_PCF': 'PC/ pathway (problem-oriented) query response',
    'QBP_K13': 'Tabular response in response to QBP^Q13',
    'QBP_Q13': 'Query by parameter requesting an RTB',
    'QBP_Q15': 'Query Response',
    'QBP_Q21': 'Get person demographics',    
    'QCK_Q02': 'Query sent for deferred response',
    'QCN_J01': 'Cancel query/acknowledge message',
    'QRY_A19': 'Patient query',
    'QRY_PC4': 'PC/ problem query',
    'QRY_Q01': 'Query sent for immediate response',
    'QRY_R02': 'Query for results of observation',
    'QSB_Q16': 'Create subscription',
    'QVR_Q17': 'Query for previous events',
    'RAR_RAR': 'Pharmacy administration information query response',
    'RAS_O17': 'Pharmacy/treatment administration',
    'RCI_I05': 'Request for patient clinical information',
    'RCL_I06': 'Request/receipt of clinical data listing',
    'RDE_O11': 'Pharmacy/treatment encoded order',
    'RDS_O13': 'Pharmacy/treatment dispense',
    'RDY_K15': 'Display response in response to QBP^Q15',
    'REF_I12': 'Patient referral',
    'RER_RER': 'Pharmacy encoded order information query response',
    'RGR_RGR': 'Pharmacy dose information query response',
    'RGV_O15': 'Pharmacy/treatment give',
    'ROR_ROR': 'Pharmacy prescription order query response',
    'RPA_I08': 'Request for treatment authorization information',
    'RPI_I01': 'Request for insurance information',
    'RPI_I04': 'Request for patient demographic data',
    'RPL_I02': 'Request/receipt of patient selection display list',
    'RPR_I03': 'Request/receipt of patient selection list',
    'RQA_I08': 'Report Query Answer',
    'RQC_I05': 'Report Query Confirm',
    'RQI_I01': 'Request for insurance information',
    'RQP_I04': 'Request for patient demographic data',
    'RQQ_Q09': 'Event Replay Query',
    'RRA_O18': 'Pharmacy/treatment administration acknowledgment',
    'RRD_O14': 'Pharmacy/treatment dispense acknowledgment',
    'RRE_O12': 'Pharmacy/treatment encoded order acknowledgment',
    'RRG_O16': 'Pharmacy/treatment give acknowledgment',
    'RRI_I12': 'Patient referral',
    'RSP_K11': 'Segment pattern response in response to QBP^Q11',
    'RSP_K21': 'Get person demographics respons',
    'RSP_K23': 'Get corresponding identifiers response',
    'RSP_K25': 'Personnel Information by Segment Response',
    'RSP_K31': 'Dispense History Response',
    'RSP_Q11': 'Query by parameter requesting an RSP',
    'RTB_K13': 'Tabular response in response to QBP^Q13',
    'SIU_S12': 'Notification of new appointment booking',
    'SIU_S13': 'Notification of appointment rescheduling',
    'SIU_S14': 'Notification of appointment modification',
    'SIU_S15': 'Notification of appointment cancellation',
    'SIU_S16': 'Notification of appointment discontinuation',
    'SIU_S17': 'Notification of appointment deletion',
    'SIU_S18': 'Notification of addition on appointment',
    'SIU_S19': 'Notification of modification on appointment',
    'SIU_S20': 'Notification of cancellation on appointment',
    'SIU_S21': 'Notification of discontinuation on appointment',
    'SIU_S22': 'Notification of deletion on appointment',
    'SIU_S23': 'Notification of blocked schedule time slot(s)',
    'SIU_S24': 'Notification of opened ("unblocked") schedule time slot(s)',
    'SIU_S26': 'Notification that patient did not show up for schedule appointment',
    'SPQ_Q08': 'Stored procedure request',
    'SQM_S25': 'SQM/Schedule query message and response',
    'SQR_S25': 'SQR/Schedule query message and response',
    'SRM_S01': 'SRM/Request new appointment booking',
    'SRR_S01': 'SRR/Request new appointment booking',
    'SSR_U04': 'Specimen Status Request',
    'SSU_U03': 'Specimen Status Update',
    'SUR_P09': 'Summary product experience report',
    'TBR_R08': 'Tabular Data Response',
    'TCU_U10': 'Automated equipment test code settings update',
    'UDM_Q05': 'Unsolicited display update message',
    'VQQ_Q07': 'Virtual table query',
    'VXQ_V01': 'Query for vaccination record',
    'VXR_V03': 'Vaccination record response',
    'VXU_V04': 'Unsolicited vaccination record update',
    'VXX_V02': 'Response to vaccination query'
}


hl7_segment_names = {
    'MSH': 'Message Header',
    'SFT': 'Software Segment',
    'UAC': 'User Authentication',
    'MSA': 'Message Acknowledgment',
    'ERR': 'Error',
    'EVN': 'Event Type',
    'PID': 'Patient Identification',
    'PD1': 'Patient Demographics',
    'ARV': 'Authorization Information',
    'ROL': 'Role',
    'NK1': 'Next of Kin',
    'PV1': 'Patient Visit',
    'PV2': 'Additional Patient Visit Information',
    'DB1': 'Disability Information',
    'OBX': 'Observation Result',
    'AL1': 'Allergy Information',
    'DG1': 'Diagnosis',
    'DRG': 'Diagnosis Related Group',
    'GT1': 'Guarantor Information',
    'ACC': 'Accident Information',
    'UB1': 'Uniform Billing',
    'UB2': 'Uniform Billing Additional',
    'PDA': 'Patient Death',
    'MRG': 'Merge Patient',
    'NPU': 'Nursing Unit',
    'ADT': 'Admit/Discharge/Transfer',
    'ARQ': 'Appointment Request',
    'ARP': 'Appointment Response',
    'PPR': 'Pharmacy Prescription',
    'PPA': 'Pharmacy Administration',
    'RSP': 'Response',
    'SRM': 'Scheduling Request Message',
    'SPM': 'Scheduling Response Message',
    'EAC': 'Equipment Account',
    'EAP': 'Equipment Profile',
    'FAC': 'Facility',
    'GTS': 'General Timing Specifications',
    'LOC': 'Location',
    'MLL': 'Medical/Legal Information',
    'NTE': 'Notes and Comments',
    'ODT': 'Order Detail',
    'OMG': 'Order Message',
    'ORD': 'Order',
    'ORDR': 'Order Detail Response',
    'ORG': 'Order Group',
    'PMU': 'Pharmacy Medication Unit',
    'PRB': 'Problem',
    'PRD': 'Problem Detail',
    'PTR': 'Patient Treatment Request',
    'PV1-1': 'Patient Visit ID',
    'PV1-2': 'Patient Visit Type',
    'PV1-3': 'Attending Doctor',
    'RSB': 'Resource Batch',
    'SSM': 'Scheduling Status Message',
    'SSF': 'Scheduled Status Follow-up',
    'TQ1': 'Timing/Quantity Information',
    'TQ2': 'Additional Timing/Quantity Information',
    'ZDS': 'Device Segment',
    'ZDG': 'Device Group',
    'ZXX': 'General Segment',
    'ZRI': 'Requested Information',
    'ZRS': 'Requested Service'
}
