hl7_message_types = {
    'ADT_A01': 'Admit/Visit Notification',
    'ADT_A02': 'Transfer a Patient',
    'ADT_A03': 'Discharge a Patient',
    'ADT_A04': 'Register a Patient',
    'ADT_A05': 'Pre-Admit a Patient',
    'ADT_A06': 'Change an Outpatient to an Inpatient',
    'ADT_A07': 'Change Patient Information',
    'ADT_A08': 'Update Patient Information',
    'ADT_A09': 'Patient Departed',
    'ADT_A10': 'Patient Leaves the Hospital',
    'ADT_A11': 'Cancel Patient Admit/Visit',
    'ADT_A12': 'Cancel Patient Discharge',
    'ADT_A13': 'Cancel Patient Transfer',
    'ADT_A14': 'Pending Patient Admit/Visit',
    'ADT_A15': 'Patient Pre-Registration',
    'ADT_A16': 'Cancel Patient Pre-Registration',
    'ADT_A17': 'Patient Visit Notification',
    'ADT_A18': 'Patient Discharge Notification',
    'ADT_A19': 'Patient Transfer Notification',
    'ADT_A20': 'Patient Registration Notification',
    'ADT_A21': 'Patient Discharge Register Notification',
    'ADT_A22': 'Patient Transfer Register Notification',
    'ADT_A23': 'Delete a Patient Record',
    'ADT_A24': 'Link Patient Information',
    'ADT_A25': 'Cancel Patient Information Link',
    'ADT_A26': 'Update Patient Information Link',
    'ADT_A27': 'Merge Patient Records',
    'ADT_A28': 'Merge Patient Records Acknowledgment',
    'ADT_A29': 'Patient Inquiry',
    'ADT_A30': 'Patient Merge Notification',
    'ADT_A31': 'Cancel Patient Merge Notification',
    'ADT_A32': 'Patient Merge Query',
    'ADT_A33': 'Update Patient Merge Notification',
    'ADT_A34': 'Patient Merge Acknowledgment',
    'ADT_A35': 'Patient Merge Acknowledgment Response',
    'ADT_A36': 'Cancel Patient Merge Query',
    'ADT_A37': 'Patient Merge Query Response',
    'ADT_A38': 'Request to Merge Patient Records',  # Added ADT_A38
    'ACK': 'Message Acknowledgment',
    'ORM_O01': 'Order Message',
    'ORR_O02': 'Order Response',
    'ORD_O01': 'Order Message',
    'ORU_R01': 'Observation Result',
    'ORU_R02': 'Observation Result Response',
    'MDM_T01': 'Medical Document Management',
    'MDM_T02': 'Medical Document Management Acknowledgment',
    'RSP_K11': 'Query Response for Pharmacy',
    'RSP_K21': 'Query Response for Laboratory',
    'EVN_O01': 'Event Message',
    'RPI_I01': 'Patient Information Message',
    'RQI_I01': 'Request for Query Information',
    'EQQ_Q02': 'Request for Event Query',
    'BAR_P01': 'Barred Patient Request',
    'BAR_P02': 'Patient Request Message',
    'BAR_P03': 'Patient Query Response',
    'MFQ_M01': 'Master File Query',
    'RPR_I02': 'Request for Response Information',
    'PTR_I05': 'Patient Treatment Record',
    'RQC_K11': 'Request for Query Clinical',
    'RQR_R01': 'Query Response for Referrals',
    'RSG': 'Response to Message Acknowledgment',
    'MSA': 'Message Acknowledgment Response',
    'RPA_I08': 'Authorization for a Referral',
    'RPA_O02': 'Referral Outcome Message',
    'RQC_R01': 'Request for Clinical Query',
    'RQR_R02': 'Query Response for Referrals',
    'ADR_A19': 'Adverse Drug Reaction Notification',
    'RAP_I11': 'Patient Admission Report',
    'RAP_O02': 'Patient Admission Report Acknowledgment',
    'PPR_P03': 'Patient Pharmacy Record',
    'PPR_P04': 'Patient Pharmacy Order',
    'RPD_I08': 'Patient Information Query Response'
}

hl7_segment_names = {
    'MSH': 'Message Header',
    'SFT': 'Software Segment',
    'UAC': 'User Authentication',
    'MSA': 'Message Acknowledgment',
    'ERR': 'Error',
    'EVN': 'Event Type',
    'PID': 'Patient Identification',
    'PD1': 'Patient Demographics',
    'ARV': 'Authorization Information',
    'ROL': 'Role',
    'NK1': 'Next of Kin',
    'PV1': 'Patient Visit',
    'PV2': 'Additional Patient Visit Information',
    'DB1': 'Disability Information',
    'OBX': 'Observation Result',
    'AL1': 'Allergy Information',
    'DG1': 'Diagnosis',
    'DRG': 'Diagnosis Related Group',
    'GT1': 'Guarantor Information',
    'ACC': 'Accident Information',
    'UB1': 'Uniform Billing',
    'UB2': 'Uniform Billing Additional',
    'PDA': 'Patient Death',
    'MRG': 'Merge Patient',
    'NPU': 'Nursing Unit',
    'ADT': 'Admit/Discharge/Transfer',
    'ARQ': 'Appointment Request',
    'ARP': 'Appointment Response',
    'PPR': 'Pharmacy Prescription',
    'PPA': 'Pharmacy Administration',
    'RSP': 'Response',
    'SRM': 'Scheduling Request Message',
    'SPM': 'Scheduling Response Message',
    'EAC': 'Equipment Account',
    'EAP': 'Equipment Profile',
    'FAC': 'Facility',
    'GTS': 'General Timing Specifications',
    'LOC': 'Location',
    'MLL': 'Medical/Legal Information',
    'NTE': 'Notes and Comments',
    'ODT': 'Order Detail',
    'OMG': 'Order Message',
    'ORD': 'Order',
    'ORDR': 'Order Detail Response',
    'ORG': 'Order Group',
    'PMU': 'Pharmacy Medication Unit',
    'PRB': 'Problem',
    'PRD': 'Problem Detail',
    'PTR': 'Patient Treatment Request',
    'PV1-1': 'Patient Visit ID',
    'PV1-2': 'Patient Visit Type',
    'PV1-3': 'Attending Doctor',
    'RSB': 'Resource Batch',
    'SSM': 'Scheduling Status Message',
    'SSF': 'Scheduled Status Follow-up',
    'SSM': 'Service Scheduling Message',
    'TQ1': 'Timing/Quantity Information',
    'TQ2': 'Additional Timing/Quantity Information',
    'ZDS': 'Device Segment',
    'ZDG': 'Device Group',
    'ZXX': 'General Segment',
    'ZRI': 'Requested Information',
    'ZRS': 'Requested Service'
}
